### ISSUE TITLE
NITC-CCC Provisional Members 

### ISSUE THREAD

**Issue by Shahraaz** [NITC-CCC/chapter#4]
This document aims to convey the process of the conversion process of Provisional Members to  Members

For the purpose of Document Members are classified into three parts:

1. Members: Current members of NITC CCC
2. Provisional Members: Members present in [this sheet](https://docs.google.com/spreadsheets/d/1DaYqRBiiSdVIVkDowU0eRbyr6IplMCAsXlfo0FrEeTg/edit#gid=0)
3. Participants: All others

The decision on the conversion of Provisional Members to  Members will be 2 weeks based on:

1. Their participation & performance in contests Codeforces, Atcoder, ICPC Mirrors .. etc.
2. Their involvement in workshops and Events.

To Elaborate on Workshops:

- Weekly ICPC mirrors on Sundays, Provisional Members must participate in a team
- Weekly ICPC mirrors upsolve session on Saturdays
- Weekly CP workshop participation, easy topics will be given as homework before the workshop which will be prerequisites to workshops

**Comment by tarun388** [comment]
I hope team participation does not restrict to only provisional members in the team.
